# Target specific macros
TARGET = command_sample
TARGET_SOURCES = \
	command_sample.c \
	command.c \
	encoder.c \
	decoder.c \
	byte_buffer.c \
	command_factory.c \
  command_c.c \
	bluetooth.c

TOPPERS_OSEK_OIL_SOURCE = ./command_sample.oil

# Don't modify below part
O_PATH ?= build
include ../../ecrobot/ecrobot.mak
